# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    # Desactiva todos los tipos de advertencias y recomendaciones
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    todo: ignore
    deprecated_member_use: ignore
    unnecessary_new: ignore
    unnecessary_this: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_locals: ignore
    prefer_const_declarations: ignore
    avoid_print: ignore
    avoid_unnecessary_containers: ignore
    prefer_typing_uninitialized_variables: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_late: ignore
    unnecessary_null_aware_assignments: ignore
    unnecessary_null_in_if_null_operators: ignore
    unnecessary_overrides: ignore
    unnecessary_parenthesis: ignore
    unnecessary_statements: ignore
    unnecessary_string_interpolations: ignore
    unnecessary_string_escapes: ignore
    use_key_in_widget_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
    prefer_final_fields: ignore
    prefer_final_in_for_each: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_generic_function_type_aliases: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    prefer_inlined_adds: ignore
    prefer_interpolation_to_compose_strings: ignore
    prefer_is_empty: ignore
    prefer_is_not_empty: ignore
    prefer_iterable_whereType: ignore
    prefer_null_aware_operators: ignore
    prefer_single_quotes: ignore
    prefer_spread_collections: ignore
    recursive_getters: ignore
    slash_for_doc_comments: ignore
    sort_child_properties_last: ignore
    sort_constructors_first: ignore
    sort_unnamed_constructors_first: ignore
    type_annotate_public_apis: ignore
    type_init_formals: ignore
    unawaited_futures: ignore
    unnecessary_await_in_return: ignore
    unnecessary_const: ignore
    unnecessary_getters_setters: ignore
    unnecessary_lambdas: ignore
    valid_regexps: ignore
    void_checks: ignore
    always_declare_return_types: ignore
    always_put_control_body_on_new_line: ignore
    always_put_required_named_parameters_first: ignore
    always_require_non_null_named_parameters: ignore
    always_specify_types: ignore
    annotate_overrides: ignore
    avoid_annotating_with_dynamic: ignore
    avoid_as: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_catching_errors: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_double_and_int_checks: ignore
    avoid_dynamic_calls: ignore
    avoid_empty_else: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    avoid_escaping_inner_quotes: ignore
    avoid_field_initializers_in_const_classes: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_implementing_value_types: ignore
    avoid_init_to_null: ignore
    avoid_js_rounded_ints: ignore
    avoid_multiple_declarations_per_line: ignore
    avoid_null_checks_in_equality_operators: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_private_typedef_functions: ignore
    avoid_redundant_argument_values: ignore
    avoid_relative_lib_imports: ignore
    avoid_return_types_on_setters: ignore
    avoid_returning_null: ignore
    avoid_returning_null_for_future: ignore
    avoid_returning_null_for_void: ignore
    avoid_returning_this: ignore
    avoid_setters_without_getters: ignore
    avoid_shadowing_type_parameters: ignore
    avoid_single_cascade_in_expression_statements: ignore
    avoid_slow_async_io: ignore
    avoid_types_as_parameter_names: ignore
    avoid_types_on_closure_parameters: ignore
    await_only_futures: ignore
    camel_case_extensions: ignore
    camel_case_types: ignore
    cancel_subscriptions: ignore
    cascade_invocations: ignore
    cast_nullable_to_non_nullable: ignore
    close_sinks: ignore
    comment_references: ignore
    constant_identifier_names: ignore
    control_flow_in_finally: ignore
    curly_braces_in_flow_control_structures: ignore
    diagnostic_describe_all_properties: ignore
    directives_ordering: ignore
    do_not_use_environment: ignore
    empty_catches: ignore
    empty_constructor_bodies: ignore
    empty_statements: ignore
    file_names: ignore
    flutter_style_todos: ignore
    hash_and_equals: ignore
    implementation_imports: ignore
    invariant_booleans: ignore
    iterable_contains_unrelated_type: ignore
    join_return_with_assignment: ignore
    leading_newlines_in_multiline_strings: ignore
    library_names: ignore
    library_prefixes: ignore
    lines_longer_than_80_chars: ignore
    list_remove_unrelated_type: ignore
    literal_only_boolean_expressions: ignore
    missing_whitespace_between_adjacent_strings: ignore
    no_adjacent_strings_in_list: ignore
    no_duplicate_case_values: ignore
    no_leading_underscores_for_local_identifiers: ignore
    no_logic_in_create_state: ignore
    no_runtimeType_toString: ignore
    non_constant_identifier_names: ignore
    null_closures: ignore
    omit_local_variable_types: ignore
    one_member_abstracts: ignore
    only_throw_errors: ignore
    overridden_fields: ignore
    package_api_docs: ignore
    package_names: ignore
    package_prefixed_library_names: ignore
    parameter_assignments: ignore
    prefer_adjacent_string_concatenation: ignore
    prefer_asserts_in_initializer_lists: ignore
    prefer_bool_in_asserts: ignore
    prefer_collection_literals: ignore
    prefer_conditional_assignment: ignore
    prefer_contains: ignore
    prefer_double_quotes: ignore
    prefer_equal_for_default_values: ignore
    prefer_expression_function_bodies: ignore
    prefer_for_elements_to_map_fromIterable: ignore
    prefer_foreach: ignore
    prefer_int_literals: ignore
    test_types_in_equals: ignore
    throw_in_finally: ignore
    unnecessary_final: ignore